version: '3.7'
services:

  mariadb:
    image: mariadb:10.4.6
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=root
    volumes:
     - ./db_volumes:/var/lib/mysql
     - ./db_volumes/conf.d:/etc/mysql/conf.d
    ports:
     - '3307:3306'
